# Generated by Django 4.2.14 on 2025-04-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0005_remove_jobapplication_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="job_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
