# Generated by Django 4.2.14 on 2025-04-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tracker",
            "0007_rename_application_date_jobapplication_applied_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Applied", "Applied"),
                    ("Not Applied", "Not Applied"),
                    ("Interview Scheduled", "Interview Scheduled"),
                    ("Offer Received", "Offer Received"),
                    ("Rejected", "Rejected"),
                    ("Accepted", "Accepted"),
                ],
                default="Applied",
                max_length=50,
            ),
        ),
    ]
