# Generated by Django 4.2.14 on 2025-04-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0008_alter_jobapplication_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Applied", "Applied"),
                    ("Not Applied", "Not Applied"),
                    ("Interview Scheduled", "Interview Scheduled"),
                    ("Exam Scheduled", "Exam Scheduled"),
                    ("Offer Received", "Offer Received"),
                    ("Rejected", "Rejected"),
                    ("Accepted", "Accepted"),
                ],
                default="Applied",
                max_length=50,
            ),
        ),
    ]
